name: llm-playground
services:
  ollama:
    image: ollama/ollama
    restart: unless-stopped
    ports:
      - 11434:11434
    volumes:
      - ollama_data:/root/.ollama
  
  web:
    image: ghcr.io/open-webui/open-webui:ollama
    volumes:
      - ollama_data:/root/.ollama
      - open-webui_data:/app/backend/data
    restart: unless-stopped
    depends_on:
      - ollama
    ports:
      - 3000:8080
    environment:
      - gpus=all
volumes:
  # will be stored under /var/lib/docker/volumes/llm-playground_ollama_data/
  ollama_data:
  # will be stored under /var/lib/docker/volumes/llm-playground_open-webui_data/
  open-webui_data:
