name: llm-playground
services:
  web:
    image: ghcr.io/open-webui/open-webui:ollama
    volumes:
      - ollama_data:/root/.ollama
      - open-webui_data:/app/backend/data
    restart: unless-stopped
    ports:
      - 3000:8080
    environment:
      - WEBUI_AUTH=False # turn off user login requirement
      # security settings
      - cap_add=SYS_NICE
      - cap_drop=ALL
      - security_opt=no-new-privileges
    memswap_limit: 8G
    deploy:
      resources:
        limits:
          cpus: "4.0"
          memory: 8G
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

volumes:
  # will be stored under /var/lib/docker/volumes/llm-playground_ollama_data/
  ollama_data:
  # will be stored under /var/lib/docker/volumes/llm-playground_open-webui_data/
  open-webui_data:
