name: node-red
services:
  server:
    image: nodered/node-red
    ports:
      - 1880:1880
    volumes:
      - data:/data
      - ./uploads:/uploads
volumes:
  # will be stored under /var/lib/docker/volumes/node-red_data/
  data: