name: mysql
services:
  server:
    image: mysql:8.4
    ports:
      - 3306:3306
    volumes:
      - data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
volumes:
  # will be stored under /var/lib/docker/volumes/mysql_data/
  data: